pipeline {
    agent none
    stages {
        agent {
            label 'node-1'
        }
        stage('build docker') {
            steps {
                sh '''
                cd website
                docker build -t php-webapp:latest .
                '''
            }
        }
        stage('run docker') {
            steps {
                sh 'docker run -d php-webapp:latest'
            }
        }
        stage('test') {
            steps {
                sh 'python3 website/test.py'
            }
        }
    }
}