pipeline {
    agent none
    stages {
        stage('build and run docker in test-server') {
            agent {
                label 'node-1'
            }
            steps {
                sh '''
                cd website
                docker build -t php-webapp:latest .
                docker run -d php-webapp:latest
                '''
            }
        }
        stage('test in test-server') {
            agent {
                label 'node-1'
            }
            steps {
                sh 'python3 website/test.py'
            }
        }
    }
}